export const jobOptions = [
    'Thực phẩm, đồ uống',
    'Kinh doanh, bán hàng',
    'Biên/ Phiên dịch',
    'Báo chí/ Truyền hình',
    'Bưu chính - Viễn thông',
    'Bảo hiểm',
    'Bất động sản',
    'Chứng khoán / Vàng / Ngoại tệ',
    'Công nghệ cao',
    'Cơ khí / Chế tạo / Tự động hóa',
    'Du lịch',
    'Dầu khí/Hóa chất',
    'Dệt may / Da giày',
    'Dịch vụ khách hàng',
    'Điện tử viễn thông',
    'Điện / Điện tử / Điện lạnh',
    'Giáo dục / Đào tạo',
    'Hoá học / Sinh học',
    'Hoạch định/Dự án',
    'Hàng gia dụng',
    'Hàng hải',
    'Hàng không',
    'Hành chính / Văn phòng',
    'In ấn / Xuất bản',
    'IT Phần cứng / Mạng',
    'IT phần mềm',
    'Khách sạn / Nhà hàng',
    'Kế toán / Kiểm toán',
    'Marketing / Truyền thông / Quảng cáo',
    'Môi trường / Xử lý chất thải',
    'Mỹ phẩm / Trang sức',
    'Mỹ thuật / Nghệ thuật / Điện ảnh',
    'Ngân hàng / Tài chính',
    'Nhân sự',
    'Nông / Lâm / Ngư nghiệp',
    'Luật/Pháp lý',
    'Quản lý chất lượng (QA/QC)',
    'Quản lý điều hành',
    'Thiết kế đồ họa',
    'Thời trang',
    'Tư vấn',
    'Tổ chức sự kiện / Quà tặng',
    'Logistics',
    'Xuất nhập khẩu',
    'Xây dựng',
    'Y tế / Dược',
    'Công nghệ Ô tô',
    'An toàn lao động',
    'Bán hàng kỹ thuật',
    'Bán lẻ / bán sỉ',
    'Bảo trì / Sửa chữa',
    'Dược phẩm / Công nghệ sinh học',
    'Địa chất / Khoáng sản',
    'Hàng cao cấp',
    'Hàng tiêu dùng',
    'Kiến trúc',
    'Phi chính phủ / Phi lợi nhuận',
    'Sản phẩm công nghiệp',
    'Sản xuất',
    'Tài chính / Đầu tư',
    'Thiết kế nội thất',
    'Thư ký / Trợ lý',
    'Spa / Làm đẹp',
    'Công nghệ thông tin',
    'NGO / Phi chính phủ / Phi lợi nhuận',
    'Ngành nghề khác',
]
export const skillOptions = [
    ".NET",
    "3D Artist",
    "3D Max",
    "ActionScript",
    "Agavi",
    "Agile",
    "Ajax",
    "Android",
    "AngularJS",
    "Antiryad Gx",
    "App Game Kit",
    "ASP.NET",
    "AutoCAD",
    "BattryTech",
    "Bootstrap",
    "Bridge Engineer",
    "C#",
    "C++",
    "Cacti",
    "CakePHP",
    "Ceph",
    "Cocoonjs",
    "Cocos2D",
    "CodeIgniter",
    "Construct 2",
    "CorelDRAW",
    "Corona",
    "CSS",
    "Designer",
    "Django",
    "Drupal",
    "Edgelib",
    "Elasticsearch",
    "Emo",
    "ERP",
    "Esenthel Engine",
    "FlightPHP",
    "FuelPHP",
    "Game",
    "Game Artist",
    "Game Editor",
    "GameMaker",
    "GameSalad",
    "Gideros",
    "Git",
    "Github",
    "GlusterFS",
    "HDFS",
    "HTML",
    "HTML5",
    "Illustrator",
    "iOS",
    "IT Helpdesk",
    "J2EE",
    "Java",
    "Javascript",
    "JMonkey",
    "Joomla",
    "JQuery",
    "JSON",
    "Knockout JS",
    "Laravel",
    "Libdx",
    "Linux",
    "LiveCode",
    "Lua",
    "Magento",
    "Manager",
    "MariaDB",
    "Marmalade",
    "Maya",
    "Memcached",
    "Microsoft Access",
    "MongoDB",
    "MonoGame",
    "MoSync",
    "MRTG",
    "MS SQL",
    "Multimedia Fusion 2",
    "MVC",
    "MVC5",
    "MySQL",
    "Nagios",
    "Nette",
    "Nginx",
    "NodeJS",
    "NoSQL",
    "Objective-C",
    "Odoo",
    "OOP",
    "Oracle",
    "Orx",
    "Papaya Social Game Engine",
    "Perl",
    "PhalconPHP",
    "Photoshop",
    "PHP",
    "PHPixie",
    "PlayCanvas",
    "PlayIR",
    "PopPHP",
    "PostgreSQL",
    "Product Manager",
    "Project Manager",
    "Python",
    "Redis",
    "REST API",
    "Riak",
    "Ruby on Rails",
    "SEM",
    "SEO",
    "Server-Side Scripting",
    "Sharepoint",
    "ShiVa",
    "ShiVa3D",
    "Signal R",
    "Simple MVC Framework",
    "Sketch",
    "Socket.io",
    "Sparrow",
    "SQL",
    "SQL Server",
    "Squid",
    "Starling",
    "Styncyl",
    "SVN",
    "Swift",
    "Symfony",
    "System Admin",
    "Tester",
    "UML",
    "Unity",
    "Unreal Development Kit",
    "UX/UI Design",
    "visual-basic",
    "WCF",
    "Websocket",
    "Windows Phone",
    "Leadership",
    "Teamwork",
    "Database",
    "IELTS",
    "Word",
    "Excel",
    "PowerPoint",
    "GMAT",
    "test cases",
    "test scripts",
    "test plan",
    "Google Analytics",
    "Google Webmaster tool",
    "iView",
    "iClick",
    "Facebook Ninja",
    "Rank tracker",
    "HMA",
    "Opencart",
    "Làm việc độc lập",
    "Microsoft Office",
    "Kỹ năng lãnh đạo",
    "Kỹ năng giao tiếp",
    "Làm việc nhóm",
    "Quản lý thời gian",
    "Copywriting",
    "Kỹ năng đàm phán",
    "Tổ chức sự kiện",
    "Market Research",
    "Telesales",
    "Kĩ năng phân tích tổng hợp",
    "Kỹ năng lắng nghe",
    "Docker",
    "Redux",
    "Planning",
    "Angular 2",
    "LESS",
    "SASS",
    "After Effect",
    "Google Adwords",
    "Marketing",
    "R&amp;D",
    "Project Management",
    "cs-cart",
    "bitrix",
    "Biên tập",
    "React Native",
    "webpack",
    "babel",
    "HSK",
    "CPA",
    "Tiếng Trung",
    "SCRUM",
    "evm",
    "Dựng phim",
    "Tiếng Nhật",
    "QC/QA",
    "Windows Server",
    "Oracle DataGuard",
    "C&amp;B",
    "LAN",
    "WAN",
    "CRM",
    "AFC",
    "ACCA",
    "AI",
    "VR",
    "Graphic design",
    "Java GUI Framework",
    "Oracle Database",
    "UI",
    "GIS",
    "NPI",
    "UX",
    "kafka",
    "Analytics",
    "etabs",
    "AIX platform",
    "IBM HTTP Server",
    "Business Process Analysis",
    "Tiếng Nhật N3",
    "Adobe Photoshop",
    "AWS",
    "ORM",
    "TOEIC",
    "Kỹ năng Thuyết phục",
    "Tiếng Anh giao tiếp",
    "Automation Test",
    "Struts",
    "Revit",
    "Sketchup",
    "CSS3",
    "OTC",
    "VB.NET",
    ".NET Framework",
    "MSSQL",
    "LinQ",
    "Facebook Ads",
    "Zalo ads",
    "SQLite",
    "Elixir",
    "TESOL",
    "TOEFL",
    "Quản lý nhóm",
    "Tiếng Anh thành thạo",
    "Thuyết trình",
    "Tư duy hệ thống",
    "ASP",
    "Tiếng Nhật N3",
    "Crystal Reports",
    "Hibernate",
    "Kỹ năng quản lý",
    "LabVIEW",
    "RD",
    "Tiếng Nhật N2",
    "Qt Framework",
    "Biên phiên dịch tiếng Trung",
    "pfSense",
    "Tin học văn phòng",
    "DNS",
    "Biên tập Video",
    "SolidWorks",
    "Oracle PL/SQL",
    "UIKit",
    "Core Data",
    "Blockchain",
    "Sony Vegas",
    "Tiếng Nga giao tiếp",
    "Maven",
    "Kubernetes",
    "Cocos2d-x",
    "XCode",
    "Visual Studio",
    "Cocos Studio",
    "Tiếng Nhật N4",
    "CAD/CAE",
    "Angular 4",
    "Javascript Framework",
    "Web API",
    "TypeScript",
    "Stopmotion",
    "Storyboad",
    "Message Queue",
    "Adobe Illustrator",
    "Scala",
    "Chart.JS",
    "Google APIs",
    "DI",
    "Web Socket",
    "ADO.NET",
    "Hitosoft",
    "MVC4",
    "Realm",
    "OpenGL",
    "Android SDK",
    "Android ADT",
    "CentOS",
    "Shell script",
    "Adobe Audition",
    "DaVinci",
    "Adobe Premier",
    "Moho",
    "SDLC",
    "Angular 6",
    "TOPIK 4",
    "COBOL",
    "Dịch thuật tiếng Trung",
    "Animation",
    "Apache",
    "Scraping",
    "Kendo UI",
    "Archicad",
    "Lotus Notes",
    "Slim PHP",
    "JSF",
    "VLAN",
    "Routing IP",
    "Financial office",
    "Advertising",
    "Vẽ 3D",
    "Junit",
    "Magento 2",
    "Angular JS",
    "Tiếng Nhật N1",
    "VueJS",
    "MS Outlook",
    "XHTML",
    "ISA",
    "DFS",
    "MCSA",
    "MCSE",
    "CCBA",
    "CBAP",
    "Cad",
    "Kỹ năng phỏng vấn",
    "counselor",
    "debug",
    "IOT",
    "FileMaker",
    "ReactJS",
    "ExpressJS",
    "MeanJS",
    "Restify",
    "Kỹ năng sư phạm",
    "PMP",
    "PMF",
    "CSM",
    "PSM",
    "Xử lý tình huống",
    "TBA",
    "MFĐ",
    "UPS",
    "Juniper",
    "Tiếng Nhật N2 - N1",
    "N3",
    "N1",
    "Biên phiên dịch tiếng Hàn",
    "Biên phiên dịch tiếng Anh",
    "Kỹ năng phân tích kinh doanh",
    "Angular",
    "Kỹ năng bơi lội",
    "Meteor",
    "Smartfox",
    "Kỹ năng bán hàng",
    "kỹ năng đào tạo",
    "HTTP/HTTPS",
    "FTP",
    "VNACCS",
    "Framework Django",
    "Lái xe",
    "MVP",
    "MVV",
    "Avid Media Composer",
    "Lightworks",
    "Final Cut",
    "Content write",
    "MES",
    "Flutter",
    "IELTS 6.",
    "Cimatron",
    "GUI",
    "Đàm phán thương lượng",
    "HSK4",
    "DB2",
    "Avr",
    "Angular 1",
    "Kỹ năng tuyển dụng",
    "Kỹ năng giảng dạy",
    "JLPT N3",
    "HSK5",
    "ETAB",
    "Fireframe",
    "ASTM",
    "phân tích số liệu",
    "Tiếng Hàn",
    "UCD",
    "UID",
    "Tiếng Pháp",
    "Kỹ năng đàm phán",
    "Business Analyst",
    "kỹ năng điều tra",
    "Unix",
    "Kỹ năng báo cáo",
    "Sales",
    "PR",
    "Tìm kiếm khách hàng",
    "Tư vấn",
    "Kỹ năng quản lý công việc",
    "Sales online",
    "PQA",
    "QA",
    "PLC",
    "Oracle SQL",
    "CCNA",
    "Flash",
    "LPI",
    "Tư duy logic",
    "Adobe After Effects",
    "Adobe Dreamweaver",
    "Adobe InDesign",
    "Biên phiên dịch Tiếng Nhật",
    "Jenkins",
    "MS Offices",
    "Misa",
    "Tiếng Anh đọc hiểu",
    "Adobe Premiere Pro",
    "Golang",
    "Unity 3D",
    "Cadewa",
    "Kotlin",
    "Jira",
    "Tiếng Anh cơ bản",
    "Tiếng Anh trung cấp",
    "ATSM",
    "ASME",
    "Lightroom",
    "Alige",
    "VMWare",
    "VB6",
    "Zoho Desk",
    "Big Data",
    "NLP",
    "RSpec",
    "Devise",
    "TDD",
    "CI",
    "Mocking",
    "Exploit",
    "Eclipse",
    "OOD",
    "LAMP",
    "LEMP",
    "VPSSIM",
    "Ubuntu",
    "Objective C",
    "IRP",
    "SOA",
    "Gerber",
    "Lectra",
    "Negotiation Skill",
    "Tiếng Thái",
    "Spring",
    "CAD 2D",
    "Fast",
    "Amis",
    "Angular 5",
    "Apache Spark",
    "HMTL5",
    "Figma",
    "JET",
    "Intermedidate English",
    "ABAP",
    "Tensorflow",
    "Pytorch",
    "Zbrush",
    "Sculpt",
    "Spring Framework",
    "Spring Boot",
    "BPMN",
    "Phát triển thị trường",
    "TCP/IP",
    "English",
    "HSK 6",
    "IELTS 7.0",
    "JLPT N2",
    "Ruby",
    "Tiếng Đức",
    "Tiếng Ý",
    "Tiếng Ả Rập",
    "Tiếng Bồ Đào Nha",
    "Tiếng Tây Ban Nha",
    "Tiếng Anh",
    "Adobe Premiere",
    "Full Stack",
    "XML",
    "AXure",
    "TOEIC 600",
    "JLPT N4",
    "JLPT N1",
    "IELTS 7.5",
    "Tiếng Indonesia",
    "TOEIC 550",
    "TOEIC 850",
    "IELTS 8.5",
    "HKS5",
    "HSK6",
    "IELTS 6.5",
    "TOEIC 650",
    "Tiếng Anh B2",
    "IELTS 8.0",
    "Performance Marketing",
    "Marketing Online",
    "Programming",
    "Xây dựng đội nhóm",
    "Excel cơ bản",
    "API",
    "CI/CD",
    "Adobe",
    "Quay dựng",
    "Game Balance",
    "Game Design",
    "Event Planning",
    "Public Speaking",
    "Business Development",
    "Communication",
    "zalo",
    "facebook",
    "Content Writer",
    "Sáng tạo nội dung",
    "Phân tích công việc",
    "Windows",
    "Chịu áp lực cao",
    "Direct Sale",
    "Design Thinking",
    "RESTful API",
    "Back-End Web Development",
    "RabbitMQ",
    "Setup hệ thống",
    "Nghiên cứu",
    "Tổ chức công việc",
    "Nhanh nhẹn",
    "Cẩn thận",
    "Nhiệt tình",
    "Tự tin",
    "Xây dựng mối quan hệ",
    "Thiết kế đồ họa",
    "Cởi mở",
    "Creativity",
    "People Management",
    "Quản lý con người",
    "Time Management",
    "Persuasion",
    "Khả năng thuyết phục",
    "Emotional Intelligence (EQ)",
    "Translation",
    "Video Production",
    "Corporate Communications",
    "Industrial Design",
    "Collaboration",
    "Adaptability",
    "Analytical Reasoning",
    "Sales Leadership",
    "Journalism",
    "Competitive Strategies",
    "Active listening",
    "Writing",
    "Nonverbal Communication",
    "Consulting",
    "Research",
    "Problem-solving",
    "Critical Thinking",
    "Data Analysis",
    "SEO/SEM",
    "Social Media",
    "Media Planning",
    "Channel Marketing",
    "Affiliate Marketing",
    "Online Marketing",
    "Strategic Planning",
    "Delegating Tasks",
    "Coaching",
    "Giảng dạy",
    "Negotiation",
    "Đàm phán",
    "Relationship Management",
    "Cloud Computing",
    "Data Presentation",
    "Tech Support",
    "UI/UX",
    "Software Engineering",
    "Mobile Development",
    "Scientific Computing",
    "Google",
    ".NET CLR",
    ".NET Compact Framework",
    ".com",
    ".htaccess",
    "10 Key",
    "1031 Exchanges",
    "1H NMR",
    "21 CFR",
    "21 CFR Part 11",
    "21st Century Skills",
    "2D graphics",
    "360 Degree Assessment",
    "360 Feedback",
    "3Com NBX",
    "3D Architectural Rendering",
    "3D GIS",
    "3D Graphics",
    "3D Modeling",
    "3D Rendering",
    "3D Scanning",
    "3D Seismic Interpretation",
    "3D Studio Max",
    "3D Studio Viz",
    "3D Visualization",
    "401k Rollovers",
    "4th Dimension",
    "5 Why",
    "5.1 Mixing",
    "960 Grid System",
    "@Task",
    "A-GPS",
    "A3 Thinking",
    "AAAHC",
    "AAC",
    "AACR2",
    "AAMS",
    "AAP",
    "AAR",
    "AASHTO",
    "AAT",
    "AAUS Scientific Diver",
    "ABAP Web Dynpro",
    "ABAP-OO",
    "ABB 800xA",
    "ABBYY",
    "ABBYY FineReader",
    "ABC Analysis",
    "ABC Flowcharter",
    "ABCP",
    "ABEL",
    "ABI",
    "ABLS",
    "ABO Certified",
    "ABR",
    "ABS",
    "ABV",
    "AC Nielsen",
    "ACAD",
    "ACBS",
    "ACD",
    "ACD Management",
    "ACDSee",
    "ACE",
    "ACE Certified",
    "ACE Certified Personal Trainer",
    "ACF2",
    "ACFE",
    "ACH",
    "ACI Codes",
    "ACIS",
    "ACLS",
    "ACLS Instruction",
    "ACMS",
    "ACOA",
    "ACORD",
    "ACP",
    "ACPI",
    "ACR",
    "ACSA",
    "ACSC",
    "ACSLS",
    "ACSM",
    "ACSM Health Fitness",
    "ACSP",
    "ACSR",
    "ACSS",
    "ACT CRM",
    "ADA Compliance",
    "ADABAS",
    "ADB",
    "ADB Adapter",
    "ADCs",
    "ADDIE",
    "ADDM",
    "ADE",
    "ADEA",
    "ADF",
    "ADFS",
    "ADFS 2.0",
    "ADHD Coaching",
    "API 510",
    "API 653",
    "API Development",
    "API Testing",
    "ASAP",
    "Accountants",
    "Accounting",
    "Accounts Payable",
    "Accounts Receivable",
    "Adobe Design Programs",
    "Agile Environment",
    "Agile Testing",
    "Analytical Skills",
    "Architectural Illustration",
    "Aruba Wireless",
    "Basic HTML",
    "CAPA",
    "CNC",
    "CNC Machine",
    "CNC Manufacturing",
    "CNC Programing",
    "CRM Program Management",
    "Cache Coherency",
    "Cache Object Script",
    "Camtasia",
    "Computer Vision",
    "Core Java",
    "Creative Writing",
    "Cross-cultural Communication Skills",
    "Crypto",
    "Custom Facebook Pages",
    "Customer Service",
    "Dart",
    "Data Backup Solutions",
    "Data Domain",
    "Database Marketing",
    "Digital Art",
    "Digital Media",
    "Dreamweaver",
    "ERP Software",
    "Excel Pivot",
    "FIFO",
    "Final Cut Pro",
    "Finance",
    "Food Quality",
    "Foundation Certificate in IT Service Management",
    "Foundation Design",
    "Front-end",
    "GMP",
    "German Teaching",
    "German Translation",
    "Group Purchasing",
    "Heroku",
    "IT Recruitment",
    "Illustration",
    "Import/Export Operations",
    "InDesign",
    "Indirect Purchasing",
    "Internet Explorer",
    "Interviews",
    "JMeter",
    "JPA",
    "Java Web Services",
    "JavaScript Libraries",
    "Load Testing",
    "Mac OS X Server",
    "Manual Testing",
    "Microsoft CRM",
    "Microsoft Certified Technology",
    "Microsoft Dynamics AX",
    "Microsoft Excel",
    "Microsoft Technologies",
    "Microsoft Word",
    "Mobile Games",
    "Mobile Internet",
    "Motion Graphic Design",
    "Motion Graphics",
    "MySQL Cluster",
    "PHP Applications",
    "PHP Frameworks",
    "PKCS",
    "PTS",
    "Pdf",
    "Premiere",
    "Procurement",
    "Project Coordination",
    "Project Purchasing",
    "Purchasing Negotiation",
    "Purchasing Processes",
    "QC Tools",
    "Quality Control",
    "RNO",
    "Routers",
    "SAP",
    "SAP BI",
    "STLC",
    "Sales Management",
    "Selenium",
    "Selenium Testing",
    "Social Media Marketing",
    "Sony Vegas Video",
    "Spine",
    "Spring MVC",
    "Sumif",
    "Tax Accounting",
    "User Research",
    "VPN",
    "Video Editing",
    "Vray",
    "WPF",
    "Wacom Tablet",
    "Wholesale Purchasing",
    "WinForms",
    "YouTube",
    "",
    "ANOVA",
    "ASP.NET MVC",
    "Academic Development",
    "Academic Editing",
    "Academic English",
    "Account Management",
    "Adaptive Learning",
    "Administration",
    "Advertising Sales",
    "After Effects",
    "xCAT",
    "xCP",
    "xPC Target",
    "xPON",
    "xPression",
    "xUnit",
    "zLinux",
    "zSeries",
    "Giao tiếp",
    "Tư duy sáng tạo",
    "Phân tích dữ liệu",
    "Wordpress",
    "Adobe Acrobat",
    "Bảo Trì Hệ Thống",
    "Sửa Chữa",
    "Bảo Trì Điện",
    "Lập Kế Hoạch",
    "Lắp Đặt Hệ Thống",
    "Sửa Chữa Máy Móc",
    "Manual Tester",
    "Kiểm Thử",
    "Testing",
    "Kế Toán Tổng Hợp",
    "Phân Tích Báo Cáo Tài Chính",
    "Outlook",
    "sale",
    "chăm sóc khách hàng",
    "giải quyết vấn đề",
    "bất động sản",
    "nội thất",
    "matrix",
    "artcam",
    "rhino",
    "soldworks",
    "jd paint",
    "Chuyên Viên Đào Tạo",
    "Content Creator Tiktok",
    "Nghiên Cứu Và Phát Triển Sản Phẩm",
    "Quản Trị Hệ Thống",
    "Thuyết Phục Khách Hàng",
    "Tư Vấn Bán Hàng",
    "Quản Trị Kinh Doanh",
    "Bán Hàng",
    "Đánh Giá Thị Trường",
    "Quản Lý Đội Ngũ",
    "Hoạch Định Chiến Lược",
    "Thu Hồi Nợ",
    "Xử Lý Nợ",
    "Lễ Tân",
    "SEO Web",
    "Quản Trị Nhân Sự",
    "Quản Trị Nguồn Nhân Lực",
    "Đánh Giá Ứng Viên",
    "Tuyển Dụng Nhân Sự",
    "Xây Dựng Nội Dung",
    "Admin",
    "Kinh Doanh",
    "Quản Lý",
    "Quản Lý Dự Án",
    "Quản Lý Team",
    "Giáo Viên",
    "Dạy Tiếng Anh",
    "Ngành Ngôn Anh",
    "Digital Marketing",
    "Tài Chính",
    "Thư Ký",
    "Soạn Thảo Văn Bản",
    "Kiểm Soát Chất Lượng",
    "Tư Vấn Và Chăm Sóc Khách Hàng",
    "Vi Tính Văn Phòng",
    "ngân hàng",
    "tín dụng",
    "Chụp ảnh",
    "Quay video nét",
    "Sử dụng các công cụ chỉnh sửa cơ bản",
    "Kế Toán",
    "Tài Chính Kế Toán",
    "Hạch Toán",
    "Tin Học",
    "Hệ Thống Kế Toán",
    "Xuất Nhập Khẩu",
    "Khai Báo Hải Quan",
    "Content Creator",
    "Thiết Kế",
    "Power Point",
    "Ms Excel",
    "Ms Word",
    "Tốtnhanh Nhẹn",
    "Nhɑnh Nhẹn",
    "Angular 13",
    "Cskh",
    "Phân Tích Thị Trường",
    "Tư Vấn Dịch Vụ",
    "Truyền Thông",
    "Quản Lý Marketing",
    "Edit Video",
    "Vẽ Tay",
    "Kiểm Soát Nội Bộ",
    "Kiểm soát vận hành",
    "Content SEO",
    "Báo Chí",
    "Quản Lý Fanpage",
    "Thiết Kế Landing Page",
    "Viết Kịch Bản",
    "Chụp Hình",
    "Landing Page",
    "Hành Chính Nhân Sự",
    "dịch vụ khách hàng",
    "Quan Hệ Khách Hàng",
    "Chạy Quảng Cáo",
    "Quảng Cáo Facebook",
    "Nghiệp Vụ Kế Toán",
    "Kế Toán Kho",
    "Luật",
    "Kế Toán Kiểm Toán",
    "Tổng Hợp Dữ Liệu",
    "Báo Cáo Quản Trị",
    "Luật Thuế",
    "Giám Sát Hiện Trường",
    "Sale Admin",
    "Lưu Trữ Hồ Sơ",
    "Trợ Lý Kinh Doanh",
    "Xử Lý Số Liệu",
    "Hỗ Trợ Kinh Doanh",
    "Thương Mại",
    "Xây Dựng Thương Hiệu",
    "Đánh Giá Nhân Sự",
    "Quản Lý Hồ Sơ",
    "Logistics"
]
export const expOptions = [
    {
        label: 'Chưa có kinh nghiệm',
        value: 0,
    },
    {
        label: 'Dưới 1 năm kinh nghiệm',
        value: 1,
    },
    {
        label: '1 năm',
        value: 2,
    },
    {
        label: '2 năm',
        value: 3,
    },
    {
        label: '4 năm',
        value: 4,
    },
    {
        label: '5 năm',
        value: 5,
    },
    {
        label: 'Trên 5 năm',
        value: 6,
    },
]
export const jobTypeOptions = [
    {
        label: 'Chọn loại hình công việc',
        value: null,
    },
    {
        label: 'Full time',
        value: 0,
    },
    {
        label: 'Part time',
        value: 1,
    },
    {
        label: 'Hybrid',
        value: 2,
    },
    {
        label: 'Remote',
        value: 3,
    },
]